/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in scaffolded apps. It is checked in here
// so TypeScript works before the first local Next.js run.
